name: Deploy to personal site
on: [push]
jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    environment: Dionysopoulos.me
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SSH Server Deploy
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          scp_source: joomla_extensions_development.xml
          scp_target: ${{ secrets.SSH_PATH }}