name: Deploy to personal site
on: [push]
jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    environment: Dionysopoulos.me
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sections Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "sections/advice.xml,sections/components.xml,sections/concepts.xml,sections/fdl.xml,sections/gpl.xml,sections/modules.xml,sections/plugins.xml,sections/preface.xml,sections/templates.xml"
          target: ${{ secrets.SSH_PATH_SECTIONS }}
      - name: Main XML File Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "joomla_extensions_development.xml"
          target: ${{ secrets.SSH_PATH }}